[profile.default]
optimizer = true
optimizer_runs = 200
evm_version = "istanbul"
via_ir = false
[profile.default.optimizer_details]
yul = false
remappings = ["forge-std=lib/forge-std/src/"]
fs_permissions = [{ access = "read-write", path = "./" }]
